# This config file is used by ros2_control
/**:
  controller_manager:
    ros__parameters:
      update_rate: 100  # Hz

      upper_arm_controller: # original controller
        type: joint_trajectory_controller/JointTrajectoryController

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

  upper_arm_controller:
    ros__parameters:
      joints:
        - swing_joint
        - boom_joint
        - arm_joint
        - bucket_joint
        - bucket_end_joint
      command_interfaces:
        # - position
        # - velocity
        - effort
      state_interfaces:
        - position
        - velocity
      # gains: # TODO: Fix for zx200
      #   swing_joint: {p: 0.75, i: 0.0, d: 0.05}
      #   boom_joint: {p: 4.2, i: 0.0, d: 0.15}
      #   arm_joint: {p: 4.1, i: 0.008, d: 0.025}
      #   bucket_joint: {p: 1.4, i: 0.0, d: 0.04}


