# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    upper_arm_controller: # original controller
      type: dt_compensated_joint_trajectory_controller/DTCompensatedJointTrajectoryController      
      # type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

upper_arm_controller:
  ros__parameters:
    joints:
      - swing_joint
      - boom_joint
      - arm_joint
      - bucket_joint
      - bucket_end_joint
    command_interfaces:
      # - position
      # - velocity
      - effort
    state_interfaces:
      - position
      - velocity
    gains: # TODO: Fix for zx200
      # swing_joint: {p: 0.0, i: 0.0, d: 0.0}
      # boom_joint: {p: 0.0, i: 0.0, d: 0.0}
      # arm_joint: {p: 0.0, i: 0.0, d: 0.0}
      # bucket_joint: {p: 0.0, i: 0.0, d: 0.0}
      # scales of velocity and acceleration are 1.0. Limits are defined in the joint_limits.yaml.
      swing_joint: {p: 0.3, i: 0.0, d: 0.0, angle_wraparound: true}
      boom_joint: {p: 1.7, i: 0.0, d: 0.0}
      arm_joint: {p: 1.4, i: 0.0, d: 0.0}
      bucket_joint: {p: 0.6, i: 0.0, d: 0.1}
      # zx120
      # swing_joint: {p: 0.75, i: 0.0, d: 0.05}
      # boom_joint: {p: 4.2, i: 0.0, d: 0.15}
      # arm_joint: {p: 4.1, i: 0.008, d: 0.025}
      # bucket_joint: {p: 1.4, i: 0.0, d: 0.04}
    constraints:
      goal_time: 60.0                   # Defaults to zero
      # stopped_velocity_tolerance: 0.02 # Defaults to 0.01
      swing_joint:
        # trajectory: 0.05               # Defaults to zero (ie. the tolerance is not enforced)
        goal:       0.03               # Defaults to zero (ie. the tolerance is not enforced)
      boom_joint:
        # trajectory: 0.05               # Defaults to zero (ie. the tolerance is not enforced)
        goal:       0.03               # Defaults to zero (ie. the tolerance is not enforced)
      arm_joint:
        # trajectory: 0.05               # Defaults to zero (ie. the tolerance is not enforced)
        goal:       0.03               # Defaults to zero (ie. the tolerance is not enforced)
      bucket_joint:
        # trajectory: 0.05               # Defaults to zero (ie. the tolerance is not enforced)
        goal:       0.03               # Defaults to zero (ie. the tolerance is not enforced)
      # bucket_end_joint:
      #   # trajectory: 0.05               # Defaults to zero (ie. the tolerance is not enforced)
      #   goal:       0.03               # Defaults to zero (ie. the tolerance is not enforced)
        
